image:
  tag: v0.8.0
env:
  open:
    DISABLE_API: false
  secret:
    # username for basic http authentication
    BASIC_AUTH_USER: admin
    # password for basic http authentication
    BASIC_AUTH_PASS: admin
service:
  servicename:
  type: NodePort
  # clusterIP: None
  externalPort: 8080
  nodePort:
  annotations: {}
  labels: {}


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi
persistence:
  enabled: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    cm.127.0.0.1.nip.io:
    - /
